[[language]]
name = "rust"
auto-format = true
# Optional: explicitly specify the formatter command
formatter = { command = "rustfmt" }

[editor.lsp]
display-inlay-hints = true


[language-server.rust-analyzer.config]
check = { command = "clippy" } # Use clippy instead of cargo check
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.typeHints.hideClosureInitialization = false

